##############################################################
##         Initial Encounter Configuration                  ##
## Script Generated for Undergrad class of microelectronics ##
## Generated by Matheus Moreira/Fernando Moraes - 2018      ##
##                                                          ##
## Functionalities of this script:                          ##
##  -Place standard cells                                   ##
##  -Place core pins                                        ##
##  -Perform initial route of the design                    ##
##############################################################
##Place the design
place_design

##Place pins in the chip sides
edit_pin -side Top -layer 4 -spread_type center -spacing 3 -pin {clk_i {gpio_o[0]} {gpio_o[1]} {gpio_o[2]} {gpio_o[3]} {gpio_o[4]} {gpio_o[5]} {gpio_o[6]} {gpio_o[7]} {gpio_o[8]} {gpio_o[9]} {gpio_o[10]} {gpio_o[11]} {gpio_o[12]} {gpio_o[13]} {gpio_o[14]} {gpio_o[15]} wb_we_o {wb_sel_o[0]} {wb_sel_o[1]} {wb_sel_o[2]} {wb_sel_o[3]} wb_stb_o wb_cyc_o wb_ack_i {ext_irq_i[0]} {ext_irq_i[1]} {ext_irq_i[2]} {ext_irq_i[3]} {ext_irq_i[4]} {ext_irq_i[5]} {ext_irq_i[6]} {ext_irq_i[7]} {ext_ack_o[0]} {ext_ack_o[1]} {ext_ack_o[2]} {ext_ack_o[3]} {ext_ack_o[4]} {ext_ack_o[5]} {ext_ack_o[6]} {ext_ack_o[7]}}

edit_pin -side Left -layer 3 -spread_type center -spacing 3 -pin {{gpio_i[0]} {gpio_i[1]} {gpio_i[2]} {gpio_i[3]} {gpio_i[4]} {gpio_i[5]} {gpio_i[6]} {gpio_i[7]} {gpio_i[8]} {gpio_i[9]} {gpio_i[10]} {gpio_i[11]} {gpio_i[12]} {gpio_i[13]} {gpio_i[14]} {gpio_i[15]} rst_i}

edit_pin -side Bottom -layer 4 -spread_type center -spacing 3 -pin {uart_rxd_i spi_sclk_o spi_mosi_o spi_miso_i {spi_cs_o[0]} {spi_cs_o[1]} {spi_cs_o[2]} {spi_cs_o[3]} {spi_cs_o[4]} {spi_cs_o[5]} twi_sda_io twi_scl_io {wb_dat_i[0]}{wb_dat_i[1]}{wb_dat_i[2]}{wb_dat_i[3]}{wb_dat_i[4]}{wb_dat_i[5]}{wb_dat_i[6]}{wb_dat_i[7]}{wb_dat_i[8]}{wb_dat_i[9]}{wb_dat_i[10]}{wb_dat_i[11]}{wb_dat_i[11]}{wb_dat_i[12]}{wb_dat_i[13]}{wb_dat_i[14]}{wb_dat_i[15]}{wb_dat_i[16]}{wb_dat_i[17]}{wb_dat_i[18]}{wb_dat_i[19]}{wb_dat_i[20]}{wb_dat_i[21]}{wb_dat_i[22]}{wb_dat_i[23]}{wb_dat_i[24]}{wb_dat_i[25]}{wb_dat_i[26]}{wb_dat_i[27]}{wb_dat_i[28]}{wb_dat_i[29]}{wb_dat_i[30]} {wb_dat_i[31]}}

edit_pin -side Right -layer 3 -spread_type center -spacing 3 -pin {{pwm_o[0]} {pwm_o[1]} {pwm_o[2]} {pwm_o[3]} {freq_gen_o[0]} {freq_gen_o[1]} {freq_gen_o[2]} uart_txd_o {wb_adr_o[0]}{wb_adr_o[1]}{wb_adr_o[2]}{wb_adr_o[3]}{wb_adr_o[4]}{wb_adr_o[5]}{wb_adr_o[6]}{wb_adr_o[7]}{wb_adr_o[8]}{wb_adr_o[9]}{wb_adr_o[10]}{wb_adr_o[11]}{wb_adr_o[11]}{wb_adr_o[12]}{wb_adr_o[13]}{wb_adr_o[14]}{wb_adr_o[15]}{wb_adr_o[16]}{wb_adr_o[17]}{wb_adr_o[18]}{wb_adr_o[19]}{wb_adr_o[20]}{wb_adr_o[21]}{wb_adr_o[22]}{wb_adr_o[23]}{wb_adr_o[24]}{wb_adr_o[25]}{wb_adr_o[26]}{wb_adr_o[27]}{wb_adr_o[28]}{wb_adr_o[29]}{wb_adr_o[30]} {wb_adr_o[31]}}


#ccopt_design 
#Pre-CTS opt
opt_design -pre_cts

#CTS
eval_legacy {setCTSMode -engine ck}
eval_legacy {clockDesign -specFile  Clock.ctstch -outDir clk_report}
#create_clock_tree_spec
#clock_design

#Post-CTS opt
opt_design -post_cts

report_timing
